name: Deploy on main

on:
  push:
    branches:
      - main

jobs:
  fileChanges:
    name: Check modified files
    outputs:
      run_job: ${{ steps.changes.outputs.frontend }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: check modified files
        uses: dorny/paths-filter@v2.10.2
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
  
  deployPRFrontendDraft:
    name: Deploy front-end to Netlify
    needs: fileChanges
    if: needs.fileChanges.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
        
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:ci -w frontend

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          build_directory: './frontend/dist/event-tracker-frontend'
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy ${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
